#!/bin/bash

# Vendor Restaurant Settings API - Curl Examples
# Practical examples for vendors to manage their restaurant settings

BASE_URL="http://localhost:8080/api"

echo "=========================================="
echo "Vendor Restaurant Settings - Curl Examples"
echo "=========================================="
echo ""
echo "Prerequisites:"
echo "1. Login as a vendor to get your token"
echo "2. Know your restaurant ID"
echo ""

# Login example
echo "--------------------"
echo "1. LOGIN AS VENDOR"
echo "--------------------"
echo ""
echo "curl -X POST $BASE_URL/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"username\": \"vendor1\","
echo "    \"password\": \"password123\""
echo "  }'"
echo ""
echo "# Save the token from the response"
echo "# TOKEN=\"<your_token_here>\""
echo ""

# Get restaurants
echo "--------------------"
echo "2. GET YOUR RESTAURANTS"
echo "--------------------"
echo ""
echo "curl -X GET $BASE_URL/restaurants \\"
echo "  -H 'Authorization: Bearer \$TOKEN'"
echo ""
echo "# Find your restaurant ID from the response"
echo "# RESTAURANT_ID=<your_restaurant_id>"
echo ""

# Get settings
echo "--------------------"
echo "3. GET RESTAURANT SETTINGS"
echo "--------------------"
echo ""
echo "curl -X GET $BASE_URL/vendor/restaurant/\$RESTAURANT_ID/settings \\"
echo "  -H 'Authorization: Bearer \$TOKEN'"
echo ""
echo "Example Response:"
echo "{"
echo "  \"success\": true,"
echo "  \"data\": {"
echo "    \"restaurant_id\": 1,"
echo "    \"restaurant_name\": \"Pizza Palace\","
echo "    \"average_prep_time_minutes\": 30,"
echo "    \"hours_of_operation\": {"
echo "      \"monday\": {\"open\": \"09:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"tuesday\": {\"open\": \"09:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"wednesday\": {\"open\": \"09:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"thursday\": {\"open\": \"09:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"friday\": {\"open\": \"09:00\", \"close\": \"23:00\", \"closed\": false},"
echo "      \"saturday\": {\"open\": \"10:00\", \"close\": \"23:00\", \"closed\": false},"
echo "      \"sunday\": {\"open\": \"10:00\", \"close\": \"21:00\", \"closed\": true}"
echo "    }"
echo "  }"
echo "}"
echo ""

# Update prep time only
echo "--------------------"
echo "4. UPDATE PREP TIME ONLY (PATCH)"
echo "--------------------"
echo ""
echo "curl -X PATCH $BASE_URL/vendor/restaurant/\$RESTAURANT_ID/prep-time \\"
echo "  -H 'Authorization: Bearer \$TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"average_prep_time_minutes\": 45"
echo "  }'"
echo ""
echo "Use this when you only want to update the prep time quickly."
echo "Valid range: 1-300 minutes"
echo ""

# Update full settings
echo "--------------------"
echo "5. UPDATE FULL SETTINGS (PUT)"
echo "--------------------"
echo ""
echo "curl -X PUT $BASE_URL/vendor/restaurant/\$RESTAURANT_ID/settings \\"
echo "  -H 'Authorization: Bearer \$TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"average_prep_time_minutes\": 35,"
echo "    \"hours_of_operation\": {"
echo "      \"monday\": {\"open\": \"10:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"tuesday\": {\"open\": \"10:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"wednesday\": {\"open\": \"10:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"thursday\": {\"open\": \"10:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"friday\": {\"open\": \"10:00\", \"close\": \"23:00\", \"closed\": false},"
echo "      \"saturday\": {\"open\": \"11:00\", \"close\": \"23:00\", \"closed\": false},"
echo "      \"sunday\": {\"open\": \"11:00\", \"close\": \"21:00\", \"closed\": true}"
echo "    }"
echo "  }'"
echo ""
echo "Notes:"
echo "- Both fields are optional (can update one or both)"
echo "- Time format: HH:MM (24-hour format)"
echo "- If closed: true, open/close times are ignored"
echo "- Open time must be before close time"
echo ""

# Update only hours
echo "--------------------"
echo "6. UPDATE ONLY HOURS OF OPERATION"
echo "--------------------"
echo ""
echo "curl -X PUT $BASE_URL/vendor/restaurant/\$RESTAURANT_ID/settings \\"
echo "  -H 'Authorization: Bearer \$TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"hours_of_operation\": {"
echo "      \"monday\": {\"open\": \"08:00\", \"close\": \"21:00\", \"closed\": false},"
echo "      \"tuesday\": {\"open\": \"08:00\", \"close\": \"21:00\", \"closed\": false},"
echo "      \"wednesday\": {\"open\": \"08:00\", \"close\": \"21:00\", \"closed\": false},"
echo "      \"thursday\": {\"open\": \"08:00\", \"close\": \"21:00\", \"closed\": false},"
echo "      \"friday\": {\"open\": \"08:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"saturday\": {\"open\": \"09:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"sunday\": {\"open\": \"09:00\", \"close\": \"20:00\", \"closed\": false}"
echo "    }"
echo "  }'"
echo ""

# Close on specific days
echo "--------------------"
echo "7. CLOSE ON SPECIFIC DAYS"
echo "--------------------"
echo ""
echo "curl -X PUT $BASE_URL/vendor/restaurant/\$RESTAURANT_ID/settings \\"
echo "  -H 'Authorization: Bearer \$TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"hours_of_operation\": {"
echo "      \"monday\": {\"open\": \"10:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"tuesday\": {\"open\": \"10:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"wednesday\": {\"open\": \"10:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"thursday\": {\"open\": \"10:00\", \"close\": \"22:00\", \"closed\": false},"
echo "      \"friday\": {\"open\": \"10:00\", \"close\": \"23:00\", \"closed\": false},"
echo "      \"saturday\": {\"open\": \"11:00\", \"close\": \"23:00\", \"closed\": false},"
echo "      \"sunday\": {\"open\": \"00:00\", \"close\": \"00:00\", \"closed\": true}"
echo "    }"
echo "  }'"
echo ""
echo "Note: When closed: true, the open/close times can be anything (they're ignored)"
echo ""

# Common scenarios
echo "=========================================="
echo "COMMON SCENARIOS"
echo "=========================================="
echo ""
echo "Scenario 1: Temporarily increase prep time during busy hours"
echo "  Use PATCH /prep-time with a higher value"
echo ""
echo "Scenario 2: Update hours for holidays"
echo "  Use PUT /settings with modified hours_of_operation"
echo ""
echo "Scenario 3: Close restaurant for a specific day"
echo "  Use PUT /settings and set closed: true for that day"
echo ""
echo "Scenario 4: Update both prep time and hours together"
echo "  Use PUT /settings with both fields"
echo ""

echo "=========================================="
echo "VALIDATION RULES"
echo "=========================================="
echo ""
echo "Average Prep Time:"
echo "  - Required range: 1-300 minutes"
echo "  - Integer value"
echo ""
echo "Hours of Operation:"
echo "  - Must include all 7 days"
echo "  - Time format: HH:MM (24-hour, e.g., 09:00, 14:30, 22:00)"
echo "  - Open time must be before close time (unless closed: true)"
echo "  - closed: boolean (true or false)"
echo ""
