#!/bin/bash
set -e

# Setup script for Terraform remote backend
# This creates the S3 bucket and DynamoDB table for storing Terraform state

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/backend"
INFRA_DIR="$SCRIPT_DIR/infra"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Terraform Backend Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check AWS credentials
echo "Step 1: Verifying AWS credentials..."
if ! aws sts get-caller-identity &>/dev/null; then
  echo "❌ AWS credentials not configured"
  echo ""
  echo "Please run: aws configure"
  echo "Or set AWS_PROFILE environment variable"
  exit 1
fi

AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
AWS_USER=$(aws sts get-caller-identity --query Arn --output text)
echo "✓ AWS credentials verified"
echo "  Account: $AWS_ACCOUNT"
echo "  User: $AWS_USER"
echo ""

# Check if backend already exists
echo "Step 2: Checking if backend already exists..."
cd "$BACKEND_DIR"

if [ -f "terraform.tfstate" ]; then
  echo "⚠️  Backend state file already exists"
  echo ""
  read -p "Do you want to re-create the backend? This will NOT delete existing resources. (y/n) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Skipping backend creation."
    echo "Using existing backend configuration..."
  fi
fi

# Initialize backend directory
echo ""
echo "Step 3: Initializing backend Terraform..."
terraform init -upgrade

# Plan backend changes
echo ""
echo "Step 4: Planning backend infrastructure..."
terraform plan -out=backend.tfplan

# Apply backend
echo ""
read -p "Create backend infrastructure? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "Aborted."
  rm -f backend.tfplan
  exit 0
fi

echo ""
echo "Step 5: Creating backend infrastructure..."
terraform apply backend.tfplan
rm -f backend.tfplan

# Get backend configuration
echo ""
echo "Step 6: Generating backend configuration..."
S3_BUCKET=$(terraform output -raw s3_bucket_name)
DYNAMODB_TABLE=$(terraform output -raw dynamodb_table_name)
AWS_REGION=$(terraform output -json | grep -o '"aws_region"[^}]*' | grep -o '"[^"]*"$' | tr -d '"' || echo "us-east-1")

# Create backend config file for infra
cat > "$INFRA_DIR/backend.hcl" << EOF
# Terraform Backend Configuration
# Generated by setup-backend.sh

bucket         = "$S3_BUCKET"
key            = "infra/terraform.tfstate"
region         = "$AWS_REGION"
encrypt        = true
dynamodb_table = "$DYNAMODB_TABLE"
EOF

echo "✓ Backend configuration saved to: infra/backend.hcl"

# Display summary
echo ""
terraform output setup_complete

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Next Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Navigate to infrastructure directory:"
echo "   cd infra"
echo ""
echo "2. Initialize Terraform with remote backend:"
echo "   terraform init -backend-config=backend.hcl"
echo ""
echo "3. Build Lambda packages:"
echo "   ./scripts/build-lambda.sh"
echo "   ./scripts/build-jobs-lambda.sh"
echo ""
echo "4. Configure variables:"
echo "   cp terraform.tfvars.example terraform.tfvars"
echo "   nano terraform.tfvars"
echo ""
echo "5. Deploy infrastructure:"
echo "   terraform plan"
echo "   terraform apply"
echo ""
echo "Backend setup complete! 🎉"
