# Terraform Backend Configuration
# Auto-generated by backend setup

bucket         = "delivery-app-terraform-state-dev-084374024444"
key            = "infra/terraform.tfstate"
region         = "us-east-1"
encrypt        = true
dynamodb_table = "delivery-app-terraform-locks-dev"